### ISSUE TITLE
typescript declaration error in 1.3

### ISSUE THREAD

**Issue by Einarsson** [aurelia/route-recognizer#39]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
6.11.3

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
webpack 4.6.0

* **Language:**
TypeScript 2.8.3

**Current behavior:**
Running npm build using webpack after 1.3 update causes build to fail. 

ERROR in C:/Git/APP_OpenBusiness/Web/App/node_modules/aurelia-route-recognizer/dist/aurelia-route-recognizer.d.ts
(35,13): Cannot find name 'Segment'.

ERROR in C:/Git/APP_OpenBusiness/Web/App/node_modules/aurelia-route-recognizer/dist/aurelia-route-recognizer.d.ts
(168,28): Cannot find name 'RecognizeResults'.

Probably an easy fix for you @EisenbergEffect but not sure if you've noticed it so I'll report it. Quick fix would be nice. :)

**Comment by dhanapalschandran** [comment]
@EisenbergEffect  typings\modules\aurelia-route-recognizer\index.d.ts(38,13): error TS2304: Cannot find name 'Segment'. , Could you fix it soon.

**Comment by dhanapalschandran** [comment]
@davismj Can we expect fix anytime soon

**Comment by dhanapalschandran** [comment]
I have already done that.

**Comment by davismj** [comment]
I fixed your issue immediately. As @AlexEngblom mentioned, please use 1.2.0 until it is deployed.

If you are completely blocked, please reach out directly to me on another Aurelia team member and we can provide additional support with building the master branch locally and importing the .d.ts file manually.

**Comment by dhanapalschandran** [comment]
Thanks a lot @davismj for the quick fix.
